const WordList = [
  { word: "able", hint: "Having the power, skill, or means to do something" },
  { word: "about", hint: "On the subject of; concerning" },
  { word: "absolute", hint: "Not qualified or diminished in any way; total" },
  { word: "accept", hint: "Consent to receive something offered" },
  { word: "account", hint: "A record or statement of financial expenditure" },
  { word: "achieve", hint: "Successfully bring about or reach by effort" },
  { word: "across", hint: "From one side to the other of something" },
  { word: "active", hint: "Engaging or ready to engage in physically energetic pursuits" },
  { word: "actual", hint: "Existing in fact; real" },
  { word: "address", hint: "The particulars of the place where someone lives" },
  { word: "admit", hint: "Confess to be true or to be the case" },
  { word: "advertise", hint: "Describe or draw attention to a product or event" },
  { word: "affect", hint: "Make a difference to" },
  { word: "afford", hint: "Have enough money to pay for something" },
  { word: "after", hint: "In the time following an event or another period of time" },
  { word: "afternoon", hint: "The time from noon or lunchtime to evening" },
  { word: "again", hint: "Another time; once more" },
  { word: "against", hint: "In opposition to" },
  { word: "agent", hint: "A person who acts on behalf of another person or group" },
  { word: "agree", hint: "Have the same opinion about something" },
  { word: "allow", hint: "Give permission for something to happen" },
  { word: "almost", hint: "Not quite; very nearly" },
  { word: "along", hint: "Moving in a constant direction on a path or surface" },
  { word: "already", hint: "Before or by now or the time in question" },
  { word: "alright", hint: "Satisfactory but not especially good" },
  { word: "also", hint: "In addition; too" },
  { word: "although", hint: "In spite of the fact that; even though" },
  { word: "always", hint: "At all times; on all occasions" },
  { word: "america", hint: "A country in North America" },
  { word: "amount", hint: "A quantity of something" },
  { word: "another", hint: "One more; additional" },
  { word: "answer", hint: "A response to a question" },
  { word: "apart", hint: "Separated by a distance" },
  { word: "apparent", hint: "Clearly visible or understood; obvious" },
  { word: "appear", hint: "Come into sight; become visible or noticeable" },
  { word: "apply", hint: "Make a formal application or request" },
  { word: "appoint", hint: "Assign a job or role to someone" },
  { word: "approach", hint: "Come near or nearer to something" },
  { word: "appropriate", hint: "Suitable or proper in the circumstances" },
  { word: "area", hint: "A region or part of a town, a country, or the world" },
  { word: "argue", hint: "Give reasons or cite evidence in support of an idea" },
  { word: "around", hint: "Located or situated on every side" },
  { word: "arrange", hint: "Organize or make plans for an event or activity" },
  { word: "associate", hint: "Connect someone or something with something else in one's mind" },
  { word: "assume", hint: "Suppose to be the case, without proof" },
  { word: "attend", hint: "Be present at an event" },
  { word: "authority", hint: "The power or right to give orders" },
  { word: "available", hint: "Able to be used or obtained" },
  { word: "aware", hint: "Having knowledge or perception of a situation or fact" },
  { word: "away", hint: "To or at a distance from a particular place" },
  { word: "awful", hint: "Very bad or unpleasant" },
  { word: "baby", hint: "A very young child" },
  { word: "back", hint: "The rear surface of the human body" },
  { word: "balance", hint: "An even distribution of weight" },
  { word: "ball", hint: "A spherical object used in various games" },
  { word: "bank", hint: "A financial institution where money is stored" },
  { word: "base", hint: "The lowest part or edge of something" },
  { word: "basis", hint: "The underlying support or foundation for an idea" },
  { word: "bear", hint: "A large, heavy mammal with thick fur" },
  { word: "beat", hint: "Strike repeatedly" },
  { word: "beauty", hint: "A combination of qualities that pleases the senses" },
  { word: "because", hint: "For the reason that; since" },
  { word: "become", hint: "Begin to be" },
  { word: "before", hint: "During the period of time preceding" },
  { word: "begin", hint: "Start; perform or undergo the first part of an action" },
  { word: "behind", hint: "At or to the far side of something" },
  { word: "believe", hint: "Accept as true; feel sure of the truth of" },
  { word: "benefit", hint: "An advantage or profit gained from something" },
  { word: "best", hint: "Of the most excellent or desirable type or quality" },
  { word: "between", hint: "At, into, or across the space separating two objects" },
  { word: "bill", hint: "An amount of money owed for goods supplied or services rendered" },
  { word: "birth", hint: "The emergence of a baby from the mother's body" },
  { word: "black", hint: "The very darkest color" },
  { word: "bloke", hint: "A British slang term for a man" },
  { word: "blood", hint: "The red liquid that circulates in the arteries and veins" },
  { word: "blow", hint: "A strong movement of air" },
  { word: "blue", hint: "A color between green and violet" },
  { word: "board", hint: "A long, thin, flat piece of wood or other hard material" },
  { word: "boat", hint: "A small vessel for traveling over water" },
  { word: "body", hint: "The physical structure of a person or an animal" },
  { word: "book", hint: "A set of written, printed, or blank pages fastened together" },
  { word: "both", hint: "Used to refer to two things or people" },
  { word: "bother", hint: "Take the trouble to do something" },
  { word: "bottle", hint: "A container with a narrow neck" },
  { word: "bottom", hint: "The lowest point or part of something" },
  { word: "break", hint: "Separate into pieces as a result of a blow" },
  { word: "brief", hint: "Of short duration" },
  { word: "brilliant", hint: "Exceptionally clever or talented" },
  { word: "bring", hint: "Take or go with to a place" },
  { word: "britain", hint: "A country in Europe" },
  { word: "brother", hint: "A man or boy in relation to other sons and daughters" },
  { word: "budget", hint: "An estimate of income and expenditure for a set period of time" },
  { word: "build", hint: "Construct something by putting parts together" },
  { word: "business", hint: "A person's regular occupation, profession, or trade" },
  { word: "busy", hint: "Having a great deal to do" },
  { word: "cake", hint: "An item of soft, sweet food" },
  { word: "call", hint: "Cry out to someone in order to summon them" },
  { word: "card", hint: "A piece of thick, stiff paper or thin pasteboard" },
  { word: "care", hint: "The provision of what is necessary for the health" },
  { word: "carry", hint: "Support and move someone or something from one place to another" },
  { word: "case", hint: "An instance of a particular situation" },
  { word: "catch", hint: "Intercept and hold something which has been thrown" },
  { word: "cause", hint: "A person or thing that gives rise to an action" },
  { word: "center", hint: "The middle point of a circle or sphere" },
  { word: "central", hint: "Of, at, or forming the center" },
  { word: "century", hint: "A period of one hundred years" },
  { word: "certain", hint: "Known for sure; established beyond doubt" },
  { word: "chair", hint: "A separate seat for one person, typically with a back and four legs" },
  { word: "chairman", hint: "A person chosen to preside over a meeting" },
  { word: "chance", hint: "A possibility of something happening" },
  { word: "change", hint: "Make or become different" },
  { word: "charge", hint: "Demand an amount as a price for a service" },
  { word: "check", hint: "Examine something in order to determine its accuracy" },
  { word: "child", hint: "A young human being below the age of puberty" },
  { word: "choice", hint: "An act of selecting or making a decision" },
  { word: "choose", hint: "Pick out or select someone or something as being the best" },
  { word: "church", hint: "A building used for public Christian worship" },
  { word: "city", hint: "A large town" },
  { word: "civil", hint: "Relating to ordinary citizens and their concerns" },
  { word: "claim", hint: "State or assert that something is the case" },
  { word: "class", hint: "A set or category of things having some property in common" },
  { word: "clear", hint: "Easy to perceive, understand, or interpret" },
  { word: "close", hint: "Move so as to cover an opening" },
  { word: "coach", hint: "A person who trains and instructs" },
  { word: "cold", hint: "Of or at a low or relatively low temperature" },
  { word: "college", hint: "An educational institution" },
  { word: "color", hint: "The property possessed by an object of producing different sensations on the eye" },
  { word: "come", hint: "Move or travel towards or into a place" },
  { word: "common", hint: "Occurring, found, or done often" },
  { word: "community", hint: "A group of people living in the same place or having a particular characteristic in common" },
  { word: "company", hint: "A commercial business" },
  { word: "compare", hint: "Estimate, measure, or note the similarity or dissimilarity between" },
  { word: "complete", hint: "Having all the necessary or appropriate parts" },
  { word: "computer", hint: "An electronic device for storing and processing data" },
  { word: "concern", hint: "Relate to; be about" },
  { word: "condition", hint: "The state of something with regard to its appearance" },
  { word: "conference", hint: "A formal meeting for discussion" },
  { word: "consider", hint: "Think carefully about something" },
  { word: "control", hint: "The power to influence or direct people's behavior or the course of events" },
  { word: "conversation", hint: "A talk, especially an informal one" },
  { word: "copy", hint: "A thing made to be similar or identical to another" },
  { word: "corner", hint: "A place or angle where two or more sides or edges meet" },
  { word: "cost", hint: "An amount that has to be paid or spent to buy or obtain something" },
  { word: "could", hint: "Past of can" },
  { word: "council", hint: "An advisory, deliberative, or legislative body of people formally constituted" },
  { word: "count", hint: "Determine the total number of" },
  { word: "country", hint: "A nation with its own government" },
  { word: "couple", hint: "Two individuals of the same sort considered together" },
  { word: "course", hint: "The route or direction followed by a ship, aircraft, road, or river" },
  { word: "court", hint: "A tribunal presided over by a judge" },
  { word: "cover", hint: "Put something such as a cloth or lid on top of or in front of" },
  { word: "create", hint: "Bring something into existence" },
  { word: "cross", hint: "A mark, object, or figure formed by two short intersecting lines" },
  { word: "crowd", hint: "A large number of people gathered together in a disorganized or unruly way" },
  { word: "culture", hint: "The arts and other manifestations of human intellectual achievement regarded collectively" },
  { word: "cup", hint: "A small, bowl-shaped container for drinking from, typically having a handle" },
  { word: "current", hint: "Belonging to the present time; happening or being used or done now" },
  { word: "customer", hint: "A person or organization that buys goods or services from a store or business" },
  { word: "cut", hint: "Make an opening, incision, or wound in something with a sharp-edged tool" },
  { word: "dark", hint: "With little or no light" },
  { word: "data", hint: "Facts and statistics collected together for reference or analysis" },
  { word: "date", hint: "The day of the month or year as specified by a number" },
  { word: "daughter", hint: "A girl or woman in relation to her parents" },
  { word: "dead", hint: "No longer alive" },
  { word: "deal", hint: "Take part in commercial trading of a particular commodity" },
  { word: "debate", hint: "A formal discussion on a particular topic" },
  { word: "decide", hint: "Come to a resolution in the mind as a result of consideration" },
  { word: "decision", hint: "A conclusion or resolution reached after consideration" },
  { word: "declare", hint: "Say something in a solemn and emphatic manner" },
  { word: "deep", hint: "Extending far down from the top or surface" },
  { word: "defense", hint: "The action of defending from or resisting attack" },
  { word: "degree", hint: "The amount, level, or extent to which something happens or is present" },
  { word: "department", hint: "A division of a large organization such as a government, university, or business, dealing with a specific area of activity" },
  { word: "depend", hint: "Be controlled or determined by" },
  { word: "describe", hint: "Give an account in words of someone or something" },
  { word: "design", hint: "A plan or drawing produced to show the look and function or workings of a building, garment, or other object before it is made" },
  { word: "despite", hint: "Without being affected by; in spite of" },
  { word: "detail", hint: "An individual feature, fact, or item" },
  { word: "develop", hint: "Grow or cause to grow and become more mature, advanced, or elaborate" },
  { word: "die", hint: "Stop living" },
  { word: "difference", hint: "A point or way in which people or things are not the same" },
  { word: "difficult", hint: "Needing much effort or skill to accomplish, deal with, or understand" },
  { word: "dinner", hint: "The main meal of the day, taken either around midday or in the evening" },
  { word: "direct", hint: "Extending or moving from one place to another by the shortest way without changing direction or stopping" },
  { word: "discuss", hint: "Talk about something with a person or people" },
  { word: "district", hint: "An area of a country or city, especially one regarded as a distinct unit because of a particular characteristic" },
  { word: "divide", hint: "Separate or be separated into parts" },
  { word: "doctor", hint: "A person who is qualified to treat people who are ill" },
  { word: "door", hint: "A hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle, or in the framework of a cupboard" },
  { word: "doubt", hint: "A feeling of uncertainty or lack of conviction" },
  { word: "down", hint: "Toward or in a lower place or position, especially to or on the ground or another surface" },
  { word: "draw", hint: "Produce a picture or diagram by making lines and marks" },
  { word: "dream", hint: "A series of thoughts, images, and sensations occurring in a person's mind during sleep" },
  { word: "drive", hint: "Operate and control the direction and speed of a motor vehicle" },
  { word: "drop", hint: "Let or make something fall vertically" },
  { word: "drug", hint: "A medicine or other substance which has a physiological effect when ingested or otherwise introduced into the body" },
  { word: "during", hint: "Throughout the course or duration of a period of time" },
  { word: "each", hint: "Used to refer to every one of two or more people or things, regarded and identified separately" },
  { word: "early", hint: "Happening or done before the usual or expected time" },
  { word: "earth", hint: "The planet on which we live" },
  { word: "east", hint: "The direction toward the point of the horizon where the sun rises at the equinoxes" },
  { word: "easy", hint: "Achieved without great effort" },
  { word: "economy", hint: "The state of a country or region in terms of the production and consumption of goods and services and the supply of money" },
  { word: "education", hint: "The process of receiving or giving systematic instruction, especially at a school or university" },
  { word: "effect", hint: "A change which is a result or consequence of an action or other cause" },
  { word: "effort", hint: "A vigorous or determined attempt" },
  { word: "eight", hint: "Equivalent to the product of two and four" },
  { word: "either", hint: "Used before the first of two alternatives that are being specified" },
  { word: "election", hint: "A formal and organized choice by vote of a person for a political office or other position" },
  { word: "else", hint: "In addition; besides" },
  { word: "employ", hint: "Give work to someone and pay them for it" },
  { word: "enable", hint: "Give the authority or means to do something" },
  { word: "encourage", hint: "Give support, confidence, or hope to someone" },
  { word: "end", hint: "A final part of something, especially a period of time, an activity, or a story" },
  { word: "enemy", hint: "A person who is actively opposed or hostile to someone or something" },
  { word: "enjoy", hint: "Take delight or pleasure in something" },
  { word: "enough", hint: "As much or as many as required" },
  { word: "enter", hint: "Come or go into a place" },
  { word: "entire", hint: "With no part left out; whole" },
  { word: "environment", hint: "The surroundings or conditions in which a person, animal, or plant lives" },
  { word: "equal", hint: "Being the same in quantity, size, degree, or value" },
  { word: "especially", hint: "Used to single out one person, thing, or situation over all others" },
  { word: "europe", hint: "A continent located entirely in the Northern Hemisphere and mostly in the Eastern Hemisphere" },
  { word: "even", hint: "Flat and smooth" },
  { word: "event", hint: "A thing that happens, especially one of importance" },
  { word: "ever", hint: "At any time" },
  { word: "every", hint: "Used before a singular noun to refer to all the individual members of a set" },
  { word: "evidence", hint: "The available body of facts or information indicating whether a belief or proposition is true or valid" },
  { word: "exactly", hint: "In a precise manner; accurately" },
  { word: "example", hint: "A thing characteristic of its kind or illustrating a general rule" },
  { word: "except", hint: "Not including; other than" },
  { word: "exist", hint: "Have objective reality or being" },
  { word: "expect", hint: "Regard something as likely to happen" },
  { word: "experience", hint: "Practical contact with and observation of facts or events" },
  { word: "explain", hint: "Make something clear to someone by describing it in more detail" },
  { word: "eye", hint: "Each of a pair of globular organs in the head through which people and vertebrate animals see" },
  { word: "face", hint: "The front part of a person's head from the forehead to the chin" },
  { word: "fact", hint: "A thing that is known or proved to be true" },
  { word: "fail", hint: "Be unsuccessful in achieving one's goal" },
  { word: "fair", hint: "Treating people equally without favoritism or discrimination" },
  { word: "fall", hint: "Move downward, typically rapidly and freely without control" },
  { word: "family", hint: "A group consisting of parents and children living together in a household" },
  { word: "fast", hint: "Moving or capable of moving at high speed" },
  { word: "father", hint: "A man in relation to his child or children" },
  { word: "fear", hint: "An unpleasant emotion caused by the threat of danger, pain, or harm" },
  { word: "feature", hint: "A distinctive attribute or aspect of something" },
  { word: "feel", hint: "Be aware of a person or object through touching or being touched" },
  { word: "field", hint: "An area of open land, especially one planted with crops or pasture" },
  { word: "figure", hint: "A number, especially one that forms part of official statistics or relates to the financial performance of a company" },
  { word: "fight", hint: "Take part in a violent struggle involving the exchange of physical blows or the use of weapons" },
  { word: "film", hint: "A motion picture" },
  { word: "final", hint: "Coming at the end of a series" },
  { word: "finally", hint: "After a long time, typically involving difficulty or delay" },
  { word: "finance", hint: "The management of large amounts of money, especially by governments or large companies" },
  { word: "find", hint: "Discover or perceive by chance or unexpectedly" },
  { word: "fine", hint: "Of high quality" },
  { word: "finish", hint: "Bring a task or activity to an end" },
  { word: "fire", hint: "Combustion or burning, in which substances combine chemically with oxygen" },
  { word: "firm", hint: "Having a solid, almost unyielding surface or structure" },
  { word: "first", hint: "Coming before all others in time or order" },
  { word: "fish", hint: "A limbless cold-blooded vertebrate animal with gills and fins and living wholly in water" },
  { word: "five", hint: "Equivalent to the sum of two and three" },
  { word: "flat", hint: "Having a level surface; without raised areas or indentations" },
  { word: "floor", hint: "The lower surface of a room" },
  { word: "follow", hint: "Go or come after a person or thing" },
  { word: "food", hint: "Any nutritious substance that people or animals eat or drink or that plants absorb" },
  { word: "foot", hint: "The lower extremity of the leg below the ankle, on which a person stands or walks" },
  { word: "force", hint: "Strength or energy as an attribute of physical action or movement" },
  { word: "foreign", hint: "Of, from, in, or characteristic of a country or language other than one's own" },
  { word: "forget", hint: "Fail to remember" },
  { word: "form", hint: "The visible shape or configuration of something" },
  { word: "fortune", hint: "Chance or luck as an external, arbitrary force affecting human affairs" },
  { word: "forward", hint: "In the direction that one is facing or traveling; toward the front" },
  { word: "free", hint: "Not under the control or in the power of another; able to act or be done as one wishes" },
  { word: "freedom", hint: "The power or right to act, speak, or think as one wants without hindrance or restraint" },
  { word: "friend", hint: "A person with whom one has a bond of mutual affection" },
  { word: "from", hint: "Indicating the point in space at which a journey, motion, or action starts" },
  { word: "front", hint: "The side or part of an object that presents itself to view or that is normally seen or used first" },
  { word: "full", hint: "Containing or holding as much or as many as possible" },
  { word: "function", hint: "An activity or purpose natural to or intended for a person or thing" },
  { word: "fund", hint: "A sum of money saved or made available for a particular purpose" },
  { word: "future", hint: "The time or a period of time following the moment of speaking or writing" },
  { word: "gain", hint: "Obtain or secure something desired, favorable, or profitable" },
  { word: "game", hint: "A form of play or sport, especially a competitive one played according to rules" },
  { word: "garden", hint: "A piece of ground adjoining a house, in which grass, flowers, and shrubs may be grown" },
  { word: "general", hint: "Affecting or concerning all or most people, places, or things" },
  { word: "generation", hint: "All of the people born and living at about the same time, regarded collectively" },
  { word: "get", hint: "Come to have something" },
  { word: "girl", hint: "A female child" },
  { word: "give", hint: "Freely transfer the possession of something to someone" },
  { word: "glass", hint: "A hard, brittle substance, typically transparent or translucent" },
  { word: "goal", hint: "The object of a person's ambition or effort" },
  { word: "god", hint: "A superhuman being or spirit worshiped as having power over nature or human fortunes" },
  { word: "gold", hint: "A yellow precious metal, the chemical element of atomic number 79" },
  { word: "good", hint: "To be desired or approved of" },
  { word: "government", hint: "The governing body of a nation, state, or community" },
  { word: "great", hint: "Of an extent, amount, or intensity considerably above the normal or average" },
  { word: "green", hint: "Of the color between blue and yellow in the spectrum" },
  { word: "ground", hint: "The solid surface of the earth" },
  { word: "group", hint: "A number of people or things that are located, gathered, or classed together" },
  { word: "grow", hint: "Increase in size by a natural process" },
  { word: "growth", hint: "The process of increasing in physical size" },
  { word: "guess", hint: "Estimate or suppose something without sufficient information to be sure of being correct" },
  { word: "hair", hint: "Any of the fine threadlike strands growing from the skin of humans, mammals, and some other animals" },
  { word: "half", hint: "Either of two equal or corresponding parts into which something is or can be divided" },
  { word: "hand", hint: "The end part of a person's arm beyond the wrist, including the palm, fingers, and thumb" },
  { word: "hang", hint: "Suspend or be suspended from above with the lower part dangling free" },
  { word: "happen", hint: "Take place; occur" },
  { word: "happy", hint: "Feeling or showing pleasure or contentment" },
  { word: "hard", hint: "Solid, firm, and rigid" },
  { word: "head", hint: "The upper part of the human body or the front or upper part of an animal's body" },
  { word: "health", hint: "The state of being free from illness or injury" },
  { word: "hear", hint: "Perceive with the ear the sound made by someone or something" },
  { word: "heart", hint: "A hollow muscular organ that pumps the blood through the circulatory system" },
  { word: "heat", hint: "The quality of being hot; high temperature" },
  { word: "heavy", hint: "Of great weight" },
  { word: "help", hint: "Make it easier for someone to do something by offering one's services or resources" },
  { word: "high", hint: "Of great vertical extent" },
  { word: "history", hint: "The study of past events, particularly in human affairs" },
  { word: "hold", hint: "Grasp, carry, or support with one's arms or hands" },
  { word: "home", hint: "The place where one lives permanently" },
  { word: "hope", hint: "A feeling of expectation and desire for a certain thing to happen" },
  { word: "hospital", hint: "An institution providing medical and surgical treatment and nursing care for sick or injured people" },
  { word: "hotel", hint: "An establishment providing accommodation, meals, and other services for travelers and tourists" },
  { word: "hour", hint: "A period of time equal to a twenty-fourth part of a day and night and divided into 60 minutes" },
  { word: "house", hint: "A building for human habitation" },
  { word: "however", hint: "Used to introduce a statement that contrasts with or seems to contradict something that has been said previously" },
  { word: "huge", hint: "Extremely large" },
  { word: "human", hint: "Relating to or characteristic of people or human beings" },
  { word: "hundred", hint: "The number equivalent to the product of ten and ten; ten more than ninety" },
  { word: "husband", hint: "A married man considered in relation to his spouse" },
  { word: "idea", hint: "A thought or suggestion as to a possible course of action" },
  { word: "identify", hint: "Establish or indicate who or what someone or something is" },
  { word: "imagine", hint: "Form a mental image or concept of" },
  { word: "impact", hint: "The action of one object coming forcibly into contact with another" },
  { word: "important", hint: "Of great significance or value" },
  { word: "improve", hint: "Make or become better" },
  { word: "include", hint: "Comprise or contain as part of a whole" },
  { word: "increase", hint: "Become or make greater in size, amount, or degree" },
  { word: "indeed", hint: "Used to emphasize a statement or response confirming something already suggested" },
  { word: "individual", hint: "Single; separate" },
  { word: "industry", hint: "Economic activity concerned with the processing of raw materials and manufacture of goods in factories" },
  { word: "influence", hint: "The capacity to have an effect on the character, development, or behavior of someone or something" },
  { word: "information", hint: "Facts provided or learned about something or someone" },
  { word: "inside", hint: "The inner side or surface of something" },
  { word: "instead", hint: "As an alternative or substitute" },
  { word: "institution", hint: "An organization founded for a religious, educational, professional, or social purpose" },
  { word: "interest", hint: "The feeling of wanting to know or learn about something or someone" },
  { word: "international", hint: "Existing, occurring, or carried on between nations" },
  { word: "interview", hint: "A meeting of people face to face, especially for consultation" },
  { word: "into", hint: "Expressing movement or action with the result that someone or something makes physical contact with something else" },
  { word: "involve", hint: "Have or include something as a necessary or integral part or result" },
  { word: "issue", hint: "An important topic or problem for debate or discussion" },
  { word: "item", hint: "An individual article or unit, especially one that is part of a list, collection, or set" },
  { word: "its", hint: "Belonging to or associated with a thing previously mentioned or easily identified" },
  { word: "itself", hint: "Used as the object of a verb or preposition to refer to a thing or animal previously mentioned as the subject of the clause" },
  { word: "join", hint: "Link or connect together" },
  { word: "just", hint: "Based on or behaving according to what is morally right and fair" },
  { word: "keep", hint: "Have or retain possession of" },
  { word: "kill", hint: "Cause the death of a person, animal, or other living thing" },
  { word: "kind", hint: "A group of people or things having similar characteristics" },
  { word: "king", hint: "The male ruler of an independent state" },
  { word: "knowledge", hint: "Facts, information, and skills acquired through experience or education" },
  { word: "labor", hint: "Work, especially hard physical work" },
  { word: "land", hint: "The part of the earth's surface that is not covered by water" },
  { word: "language", hint: "The method of human communication, either spoken or written" },
  { word: "large", hint: "Of considerable or relatively great size, extent, or capacity" },
  { word: "last", hint: "Coming after all others in time or order" },
  { word: "late", hint: "Doing something or taking place after the expected, proper, or usual time" },
  { word: "laugh", hint: "Make spontaneous sounds and movements of the face and body that are the instinctive expressions of lively amusement" },
  { word: "law", hint: "The system of rules that a particular country or community recognizes as regulating the actions of its members" },
  { word: "lawyer", hint: "A person who practices or studies law" },
  { word: "lead", hint: "Cause a person or animal to go with one by holding them by the hand, a halter, a rope, etc., while moving forward" },
  { word: "leader", hint: "The person who leads or commands a group, organization, or country" },
  { word: "learn", hint: "Gain or acquire knowledge of or skill in something by study, experience, or being taught" },
  { word: "least", hint: "Smallest in amount, extent, or significance" },
  { word: "leave", hint: "Go away from" },
  { word: "left", hint: "On, towards, or relating to the side of a human body or of a thing that is to the west when the person or thing is facing north" },
  { word: "leg", hint: "Each of the limbs on which a person or animal walks and stands" },
  { word: "legal", hint: "Relating to the law" },
  { word: "less", hint: "A smaller amount of" },
  { word: "let", hint: "Not prevent or forbid" },
  { word: "letter", hint: "A character representing one or more of the sounds used in speech" },
  { word: "level", hint: "A horizontal plane or line with respect to the distance above or below a given point" },
  { word: "lie", hint: "The way, direction, or position in which something lies" },
  { word: "life", hint: "The condition that distinguishes animals and plants from inorganic matter" },
  { word: "light", hint: "The natural agent that stimulates sight and makes things visible" },
  { word: "like", hint: "Having the same characteristics or qualities as" },
  { word: "likely", hint: "Such as well might happen or be true" },
  { word: "limit", hint: "A point or level beyond which something does not or may not extend or pass" },
  { word: "line", hint: "A long, narrow mark or band" },
  { word: "list", hint: "A number of connected items or names written or printed consecutively, typically one below the other" },
  { word: "listen", hint: "Give one's attention to a sound" },
  { word: "little", hint: "Small in size, amount, or degree" },
  { word: "live", hint: "Remain alive" },
  { word: "local", hint: "Relating or restricted to a particular area or one's neighborhood" },
  { word: "lock", hint: "A mechanism for keeping a door, lid, etc., fastened" },
  { word: "long", hint: "Measuring a great distance from end to end" },
  { word: "look", hint: "Direct one's gaze toward someone or something" },
  { word: "lord", hint: "Someone or something having power, authority, or influence" },
  { word: "lose", hint: "Be deprived of or cease to have or retain something" },
  { word: "loss", hint: "The fact or process of losing something or someone" },
  { word: "love", hint: "An intense feeling of deep affection" },
  { word: "low", hint: "Of less than average height from top to bottom" },
  { word: "luck", hint: "Success or failure apparently brought by chance rather than through one's own actions" },
  { word: "lunch", hint: "A meal eaten in the middle of the day" },
  { word: "machine", hint: "An apparatus using mechanical power and having several parts, each with a definite function and together performing a particular task" },
  { word: "magazine", hint: "A periodical publication containing articles and illustrations, often on a particular subject or aimed at a particular readership" },
  { word: "main", hint: "Chief in size or importance" },
  { word: "maintain", hint: "Cause or enable a condition or state of affairs to continue" },
  { word: "major", hint: "Important, serious, or significant" },
  { word: "make", hint: "Form something by putting parts together or combining substances" },
  { word: "man", hint: "An adult human male" },
  { word: "manage", hint: "Be in charge of a business, organization, or undertaking" },
  { word: "many", hint: "A large number of" },
  { word: "market", hint: "A regular gathering of people for the purchase and sale of provisions, livestock, and other commodities" },
  { word: "marriage", hint: "The legally or formally recognized union of two people as partners in a personal relationship" },
  { word: "material", hint: "The matter from which a thing is or can be made" },
  { word: "matter", hint: "The substance or substances of which any physical object consists or is composed" },
  { word: "may", hint: "Expressing possibility" },
  { word: "maybe", hint: "Perhaps; possibly" },
  { word: "mean", hint: "Intend to convey, indicate, or refer to a particular thing or notion" },
  { word: "measure", hint: "Ascertain the size, amount, or degree of something" },
  { word: "media", hint: "The main means of mass communication" },
  { word: "medical", hint: "Relating to the science or practice of medicine" },
  { word: "meet", hint: "Come into the presence or company of someone by chance or arrangement" },
  { word: "member", hint: "An individual belonging to a group such as a society or team" },
  { word: "mention", hint: "Refer to something briefly and without going into detail" },
  { word: "method", hint: "A particular procedure for accomplishing or approaching something" },
  { word: "middle", hint: "At an equal distance from the extremities of something; central" },
  { word: "might", hint: "Used to express possibility" },
  { word: "mile", hint: "A unit of linear measure equal to 1,760 yards" },
  { word: "military", hint: "Relating to or characteristic of soldiers or armed forces" },
  { word: "million", hint: "The number equivalent to the product of a thousand and a thousand" },
  { word: "mind", hint: "The element of a person that enables them to be aware of the world and their experiences" },
  { word: "minister", hint: "A member of the clergy" },
  { word: "minute", hint: "A period of time equal to sixty seconds or a sixtieth of an hour" },
  { word: "miss", hint: "Fail to hit, reach, or come into contact with something" },
  { word: "mission", hint: "An important assignment carried out for political, religious, or commercial purposes" },
  { word: "model", hint: "A three-dimensional representation of a person or thing or of a proposed structure" },
  { word: "modern", hint: "Relating to the present or recent times as opposed to the remote past" },
  { word: "moment", hint: "A very brief period of time" },
  { word: "money", hint: "A current medium of exchange in the form of coins and banknotes" },
  { word: "month", hint: "Each of the twelve named periods into which a year is divided" },
  { word: "moral", hint: "Concerned with the principles of right and wrong behavior" },
  { word: "more", hint: "A greater or additional amount or degree of" },
  { word: "morning", hint: "The period of time between midnight and noon" },
  { word: "most", hint: "Greatest in amount, quantity, or degree" },
  { word: "mother", hint: "A woman in relation to her child or children" },
  { word: "mouth", hint: "The opening and cavity in the lower part of the human face" },
  { word: "move", hint: "Go in a specified direction or manner" },
  { word: "much", hint: "A great amount or quantity of" },
  { word: "music", hint: "Vocal or instrumental sounds combined in such a way as to produce beauty of form, harmony, and expression of emotion" },
  { word: "must", hint: "Be obliged to; should" },
  { word: "name", hint: "A word or set of words by which a person or thing is known" },
  { word: "nation", hint: "A large body of people united by common descent, history, culture, or language" },
  { word: "nature", hint: "The phenomena of the physical world collectively" },
  { word: "near", hint: "At or to a short distance away" },
  { word: "necessary", hint: "Required to be done, achieved, or present" },
  { word: "need", hint: "Require something because it is essential or very important" },
  { word: "network", hint: "A group or system of interconnected people or things" },
  { word: "never", hint: "At no time in the past or future" },
  { word: "new", hint: "Produced, introduced, or discovered recently or now for the first time" },
  { word: "news", hint: "Newly received or noteworthy information, especially about recent or important events" },
  { word: "next", hint: "Coming immediately after the time of writing or speaking" },
  { word: "nice", hint: "Pleasant; agreeable" },
  { word: "night", hint: "The period from sunset to sunrise in each twenty-four hours" },
  { word: "no", hint: "Not any" },
  { word: "none", hint: "Not any" },
  { word: "normal", hint: "Conforming to a standard; usual, typical, or expected" },
  { word: "north", hint: "The direction in which a compass needle normally points, towards the horizon on the left-hand side of a person facing east" },
  { word: "not", hint: "Used with an auxiliary verb or 'be' to form the negative" },
  { word: "note", hint: "A brief record of facts, topics, or thoughts" },
  { word: "nothing", hint: "Not anything; no single thing" },
  { word: "notice", hint: "The fact of observing or paying attention to something" },
  { word: "now", hint: "At the present moment" }
]
export default WordList;